### PR TITLE
Add HACS integration

### PR DESCRIPTION
**Pull request by patrickhilker**
Just added the `hacs.json` and used it to install it in my Home Assistant instance. Works like a charm. :-) Would be happy to see this merged.

I also created a [pull request in Home Assistant Brands repo](https://github.com/home-assistant/brands/pull/3161) to make the icon and logo available (for further improvements...).

### CODE REVIEW

**Comment by patrickhilker** [comment]
Some more updates on this repo are needed to integrate it into the default hacs repos.

- [ ] Update project description (for example: Control your tedee smart lock from Home Assistant)
- [ ] Add some topics (for example: tedee, smartlock, smart-lock, lock, homeassistant, home-assistant, customcomponent, custom-component, hacs, integration, security)
- [ ] Add [default repo badge](https://hacs.xyz/docs/publish/start#badges)
- [ ] Follow [these instructions](https://hacs.xyz/docs/publish/include)

**Comment by joerg65** [comment]
Thank you very much, @patrickhilker. I will look into this next days.

**Comment by patrickhilker** [comment]
Just fixed another minor issue in the hacs integration. 😊  Let me know if you need any help.

**Comment by joerg65** [comment]
Sorry, I merged it to fast, had to revert.
Error: Repository structure for v0.0.3 is not compliant

**Comment by patrickhilker** [comment]
See https://github.com/joerg65/tedee_lock/pull/6#issuecomment-1043483612

**Pull request merged**
